### ISSUE TITLE
reproducible builds

### ISSUE THREAD

**Issue by kplimack** [metal3-io/ironic-ipa-downloader#30]
The way this container works is by downloading the latest/greatest ironic-python-agent from the upstream repo; this occurs any time the ironic deployment in kubernetes restarts and the init-container runs.  

The effects of this are

1. production systems are pulling/executing untrusted code from the internet at run-time without: scanning, code-reviews, etc
2. each time new code is pulled at runtime, compatibility issues can arise.

**Comment by dtantsur** [comment]
Ideally, we should use a fixed version of the image from RDO, but I doubt RDO keeps all its past images available. The alternative is to build images ourselves with https://opendev.org/openstack/ironic-python-agent-builder.

The title of this bug is somewhat misleading. Under reproducible builds people usually understand builds that produce exactly the same artefact from the same sources. No container builds that use a package manager satisfy that.

**Comment by Rozzii** [comment]
@kplimack Do you have a comment on the last answer or can we close the issue?
